FROM nginx:alpine
COPY ./nginx.conf /etc/nginx/nginx.conf

## Remove default nginx index page
RUN rm -rf /usr/share/nginx/html/*

# establish where Nginx should look for files
ENV RAILS_ROOT /var/www/ommo-back
# Set our working directory inside the image
WORKDIR $RAILS_ROOT

EXPOSE 80
# ENTRYPOINT ["nginx", "-g", "daemon off;"]
